name: CI

on:
  pull_request:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode 26.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'

      - name: Xcode version
        run: xcodebuild -version

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: SwiftLint
        run: swiftlint --strict

      - name: Build & Test
        shell: bash
        run: |
          set -eo pipefail

          echo "Available simulators:"
          xcrun simctl list devices available

          DEVICE_NAME="$(xcrun simctl list devices available \
            | sed -n 's/^[[:space:]]*\(iPhone[^()]*\) (.*/\1/p' \
            | head -n 1)"

          if [ -z "$DEVICE_NAME" ]; then
            echo "No iPhone Simulator found"
            exit 1
          fi

          echo "Using simulator: $DEVICE_NAME"

          xcodebuild test \
            -project RickAndMortyBrowser.xcodeproj \
            -scheme RickAndMortyBrowser \
            -destination "platform=iOS Simulator,OS=latest,name=$DEVICE_NAME"
